name: PlayerStatus
main: Theslwaja\PlayerStatus\Main
author: Theslowaja
credits: ShandyR
version: 2.0
api: 5.0.0

commands:
  player:
    permission: player.use
    
permissions:
  player.use:
    default: true
